allowBuilds:
  "@swc/core": true
  esbuild: true
  sharp: true
  supabase: true
  workerd: true
minimumReleaseAgeExclude:
  - '@blockstacking/*'
  - snarkdown-in-react
  - oxlint
  - '@oxlint/*'
  - typescript
  - '@typescript/*'
patchedDependencies:
  pixi.js: patches/pixi.js.patch
