import { inferRoomJson, type RoomJson } from "../../../model/RoomJson.ts";

import { type OriginalCampaignRoomId } from "../OriginalCampaignRoomId.ts";

export const room = inferRoomJson({
  color: { hue: "white", shade: "basic" },
  floor: "deadly",
  id: "egyptus7",
  items: {
    "block@0,0,3": {
      config: { style: "organic" },
      position: { x: 0, y: 0, z: 3 },
      type: "block",
    },
    "block@0,5,3": {
      config: { style: "organic" },
      position: { x: 0, y: 5, z: 3 },
      type: "block",
    },
    "block@0,7,3": {
      config: { style: "organic" },
      position: { x: 0, y: 7, z: 3 },
      type: "block",
    },
    "block@2,7,3": {
      config: { style: "organic" },
      position: { x: 2, y: 7, z: 3 },
      type: "block",
    },
    "block@3,0,3": {
      config: { style: "organic" },
      position: { x: 3, y: 0, z: 3 },
      type: "block",
    },
    "block@4,0,3": {
      config: { style: "organic" },
      position: { x: 4, y: 0, z: 3 },
      type: "block",
    },
    "block@7,3,3": {
      config: { style: "organic" },
      position: { x: 7, y: 3, z: 3 },
      type: "block",
    },
    "block@7,4,3": {
      config: { style: "organic" },
      position: { x: 7, y: 4, z: 3 },
      type: "block",
    },
    "block@7,7,3": {
      config: { style: "organic" },
      position: { x: 7, y: 7, z: 3 },
      type: "block",
    },
    "door@3,0,4": {
      config: { direction: "towards", toRoom: "egyptus5" },
      position: { x: 3, y: 0, z: 4 },
      type: "door",
    },
    "door@8,3,5": {
      config: { direction: "left", toRoom: "egyptus8" },
      position: { x: 8, y: 3, z: 5 },
      type: "door",
    },
    "extrablock0@0,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 0, z: 0 },
      type: "block",
    },
    "extrablock0@0,5,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 5, z: 0 },
      type: "block",
    },
    "extrablock0@0,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 7, z: 0 },
      type: "block",
    },
    "extrablock0@2,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 2, y: 7, z: 0 },
      type: "block",
    },
    "extrablock0@3,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 3, y: 0, z: 0 },
      type: "block",
    },
    "extrablock0@4,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 4, y: 0, z: 0 },
      type: "block",
    },
    "extrablock0@7,3,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 3, z: 0 },
      type: "block",
    },
    "extrablock0@7,4,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 4, z: 0 },
      type: "block",
    },
    "extrablock0@7,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 7, z: 0 },
      type: "block",
    },
    "extrablock1@0,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 0, z: 1 },
      type: "block",
    },
    "extrablock1@0,5,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 5, z: 1 },
      type: "block",
    },
    "extrablock1@0,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 7, z: 1 },
      type: "block",
    },
    "extrablock1@2,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 2, y: 7, z: 1 },
      type: "block",
    },
    "extrablock1@3,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 3, y: 0, z: 1 },
      type: "block",
    },
    "extrablock1@4,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 4, y: 0, z: 1 },
      type: "block",
    },
    "extrablock1@7,3,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 3, z: 1 },
      type: "block",
    },
    "extrablock1@7,4,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 4, z: 1 },
      type: "block",
    },
    "extrablock1@7,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 7, z: 1 },
      type: "block",
    },
    "extrablock@0,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 0, z: 2 },
      type: "block",
    },
    "extrablock@0,5,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 5, z: 2 },
      type: "block",
    },
    "extrablock@0,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 0, y: 7, z: 2 },
      type: "block",
    },
    "extrablock@2,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 2, y: 7, z: 2 },
      type: "block",
    },
    "extrablock@3,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 3, y: 0, z: 2 },
      type: "block",
    },
    "extrablock@4,0,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 4, y: 0, z: 2 },
      type: "block",
    },
    "extrablock@7,3,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 3, z: 2 },
      type: "block",
    },
    "extrablock@7,4,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 4, z: 2 },
      type: "block",
    },
    "extrablock@7,7,3": {
      config: { style: "tower" },
      isExtra: true,
      position: { x: 7, y: 7, z: 2 },
      type: "block",
    },
  },
  planet: "egyptus",
  size: { x: 8, y: 8 },
  walls: {
    away: [
      "hieroglyphics",
      "hieroglyphics",
      "sarcophagus",
      "hieroglyphics",
      "hieroglyphics",
      "sarcophagus",
      "hieroglyphics",
      "hieroglyphics",
    ],
    left: [
      "hieroglyphics",
      "sarcophagus",
      "hieroglyphics",
      "none",
      "none",
      "hieroglyphics",
      "sarcophagus",
      "hieroglyphics",
    ],
  },
}) satisfies RoomJson<"egyptus", OriginalCampaignRoomId>;
