import { inferRoomJson, type RoomJson } from "@/model/RoomJson.ts";

import { type OriginalCampaignRoomId } from "../OriginalCampaignRoomId.ts";

export const room = inferRoomJson({
  color: { hue: "white", shade: "basic" },
  floor: "moonbase",
  id: "moonbase33triple",
  items: {
    "deadlyBlock@0,10,0": {
      config: { style: "toaster" },
      position: { x: 0, y: 10, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@0,11,0": {
      config: { style: "toaster" },
      position: { x: 0, y: 11, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@0,12,0": {
      config: { style: "toaster" },
      position: { x: 0, y: 12, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@0,13,0": {
      config: { style: "toaster" },
      position: { x: 0, y: 13, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,1,0": {
      config: { style: "toaster" },
      position: { x: 11, y: 1, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,14,0": {
      config: { style: "toaster" },
      position: { x: 11, y: 14, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,2,0": {
      config: { style: "toaster" },
      position: { x: 11, y: 2, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,3,0": {
      config: { style: "toaster" },
      position: { x: 11, y: 3, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,4,0": {
      config: { style: "toaster" },
      position: { x: 11, y: 4, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,5,0": {
      config: { style: "toaster" },
      position: { x: 11, y: 5, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,9,0": {
      config: { style: "toaster" },
      position: { x: 11, y: 9, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,10,0": {
      config: { style: "toaster" },
      position: { x: 5, y: 10, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,11,0": {
      config: { style: "toaster" },
      position: { x: 5, y: 11, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,12,0": {
      config: { style: "toaster" },
      position: { x: 5, y: 12, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,13,0": {
      config: { style: "toaster" },
      position: { x: 5, y: 13, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,10,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 10, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,11,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 11, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,12,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 12, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,13,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 13, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,2,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 2, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,3,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 3, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,4,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 4, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,5,0": {
      config: { style: "toaster" },
      position: { x: 6, y: 5, z: 0 },
      type: "deadlyBlock",
    },
    "door@12,11,0": {
      config: { direction: "left", toRoom: "moonbase34" },
      position: { x: 12, y: 11, z: 0 },
      type: "door",
    },
    "door@2,16,0": {
      config: { direction: "away", toRoom: "moonbase36" },
      position: { x: 2, y: 16, z: 0 },
      type: "door",
    },
    "door@8,0,0": {
      config: { direction: "towards", toRoom: "moonbase32" },
      position: { x: 8, y: 0, z: 0 },
      type: "door",
    },
    "monster@0,10,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 0, y: 10, z: 1 },
      type: "monster",
    },
    "monster@0,11,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 0, y: 11, z: 1 },
      type: "monster",
    },
    "monster@0,12,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 0, y: 12, z: 1 },
      type: "monster",
    },
    "monster@0,13,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 0, y: 13, z: 1 },
      type: "monster",
    },
    "monster@11,1,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 11, y: 1, z: 1 },
      type: "monster",
    },
    "monster@11,14,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: true,
        which: "cyberman",
      },
      position: { x: 11, y: 14, z: 1 },
      type: "monster",
    },
    "monster@11,2,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 11, y: 2, z: 1 },
      type: "monster",
    },
    "monster@11,3,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 11, y: 3, z: 1 },
      type: "monster",
    },
    "monster@11,4,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 11, y: 4, z: 1 },
      type: "monster",
    },
    "monster@11,5,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: true,
        which: "cyberman",
      },
      position: { x: 11, y: 5, z: 1 },
      type: "monster",
    },
    "monster@11,9,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 11, y: 9, z: 1 },
      type: "monster",
    },
    "monster@5,10,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 5, y: 10, z: 1 },
      type: "monster",
    },
    "monster@5,11,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 5, y: 11, z: 1 },
      type: "monster",
    },
    "monster@5,12,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 5, y: 12, z: 1 },
      type: "monster",
    },
    "monster@5,13,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "right",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 5, y: 13, z: 1 },
      type: "monster",
    },
    "monster@6,10,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 10, z: 1 },
      type: "monster",
    },
    "monster@6,11,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 11, z: 1 },
      type: "monster",
    },
    "monster@6,12,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 12, z: 1 },
      type: "monster",
    },
    "monster@6,13,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 13, z: 1 },
      type: "monster",
    },
    "monster@6,2,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 2, z: 1 },
      type: "monster",
    },
    "monster@6,3,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 3, z: 1 },
      type: "monster",
    },
    "monster@6,4,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 4, z: 1 },
      type: "monster",
    },
    "monster@6,5,1": {
      config: {
        activated: false,
        movement: "towards-on-shortest-axis-xy4",
        startDirection: "left",
        wakes: false,
        which: "cyberman",
      },
      position: { x: 6, y: 5, z: 1 },
      type: "monster",
    },
    "wall@0,7,0": {
      config: { side: "away", style: "coil" },
      position: { x: 0, y: 7, z: 0 },
      type: "wall",
    },
    "wall@1,7,0": {
      config: { side: "away", style: "coil" },
      position: { x: 1, y: 7, z: 0 },
      type: "wall",
    },
    "wall@2,7,0": {
      config: { side: "away", style: "coil" },
      position: { x: 2, y: 7, z: 0 },
      type: "wall",
    },
    "wall@3,7,0": {
      config: { side: "away", style: "coil" },
      position: { x: 3, y: 7, z: 0 },
      type: "wall",
    },
    "wall@4,7,0": {
      config: { side: "away", style: "coil" },
      position: { x: 4, y: 7, z: 0 },
      type: "wall",
    },
    "wall@5,0,0": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 0, z: 0 },
      type: "wall",
    },
    "wall@5,1,0": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 1, z: 0 },
      type: "wall",
    },
    "wall@5,2,0": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 2, z: 0 },
      type: "wall",
    },
    "wall@5,3,0": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 3, z: 0 },
      type: "wall",
    },
    "wall@5,4,0": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 4, z: 0 },
      type: "wall",
    },
    "wall@5,5,0": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 5, z: 0 },
      type: "wall",
    },
    "wall@5,6,0": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 6, z: 0 },
      type: "wall",
    },
    "wall@5,7,0:Z2oYlvx": {
      config: { side: "away", style: "coil" },
      position: { x: 5, y: 7, z: 0 },
      type: "wall",
    },
    "wall@5,7,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 7, z: 0 },
      type: "wall",
    },
  },
  planet: "moonbase",
  size: { x: 12, y: 16 },
  walls: {
    away: [
      "window3",
      "window2",
      "none",
      "none",
      "window2",
      "window1",
      "window1",
      "coil",
      "window3",
      "window2",
      "coil",
      "window1",
    ],
    left: [
      "window2",
      "window1",
      "coil",
      "window3",
      "window2",
      "coil",
      "window2",
      "window1",
      "window2",
      "coil",
      "window3",
      "none",
      "none",
      "window3",
      "coil",
      "window1",
    ],
  },
}) satisfies RoomJson<"moonbase", OriginalCampaignRoomId>;
