import type { RoomJson } from "../../../model/modelTypes.ts";

import { type OriginalCampaignRoomId } from "../OriginalCampaignRoomId.ts";

export const room = {
  color: { hue: "white", shade: "basic" },
  floor: "moonbase",
  floorSkip: [
    { x: 5, y: 3 },
    { x: 5, y: 2 },
    { x: 5, y: 1 },
    { x: 5, y: 0 },
    { x: 5, y: -1 },
    { x: 5, y: -2 },
    { x: 5, y: -3 },
    { x: 5, y: -4 },
    { x: 5, y: -5 },
    { x: 4, y: 3 },
    { x: 4, y: 2 },
    { x: 4, y: 1 },
    { x: 4, y: 0 },
    { x: 4, y: -1 },
    { x: 4, y: -2 },
    { x: 4, y: -3 },
    { x: 4, y: -4 },
    { x: 4, y: -5 },
    { x: 3, y: 3 },
    { x: 3, y: 2 },
    { x: 3, y: 1 },
    { x: 3, y: 0 },
    { x: 3, y: -1 },
    { x: 3, y: -2 },
    { x: 3, y: -3 },
    { x: 3, y: -4 },
    { x: 3, y: -5 },
    { x: 2, y: 3 },
    { x: 2, y: 2 },
    { x: 2, y: 1 },
    { x: 2, y: 0 },
    { x: 2, y: -1 },
    { x: 2, y: -2 },
    { x: 2, y: -3 },
    { x: 2, y: -4 },
    { x: 2, y: -5 },
    { x: 1, y: 3 },
    { x: 1, y: 2 },
    { x: 1, y: 1 },
    { x: 1, y: 0 },
    { x: 1, y: -1 },
    { x: 1, y: -2 },
    { x: 1, y: -3 },
    { x: 1, y: -4 },
    { x: 1, y: -5 },
    { x: 0, y: 3 },
    { x: 0, y: 2 },
    { x: 0, y: 1 },
    { x: 0, y: 0 },
    { x: 0, y: -1 },
    { x: 0, y: -2 },
    { x: 0, y: -3 },
    { x: 0, y: -4 },
    { x: 0, y: -5 },
  ],
  id: "moonbase33triple",
  items: {
    "baddie@0,10,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 0, y: 10, z: 1 },
      type: "baddie",
    },
    "baddie@0,11,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 0, y: 11, z: 1 },
      type: "baddie",
    },
    "baddie@0,12,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 0, y: 12, z: 1 },
      type: "baddie",
    },
    "baddie@0,13,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 0, y: 13, z: 1 },
      type: "baddie",
    },
    "baddie@11,1,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 11, y: 1, z: 1 },
      type: "baddie",
    },
    "baddie@11,14,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 11, y: 14, z: 1 },
      type: "baddie",
    },
    "baddie@11,2,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 11, y: 2, z: 1 },
      type: "baddie",
    },
    "baddie@11,3,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 11, y: 3, z: 1 },
      type: "baddie",
    },
    "baddie@11,4,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 11, y: 4, z: 1 },
      type: "baddie",
    },
    "baddie@11,5,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 11, y: 5, z: 1 },
      type: "baddie",
    },
    "baddie@11,9,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 11, y: 9, z: 1 },
      type: "baddie",
    },
    "baddie@5,10,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 5, y: 10, z: 1 },
      type: "baddie",
    },
    "baddie@5,11,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 5, y: 11, z: 1 },
      type: "baddie",
    },
    "baddie@5,12,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 5, y: 12, z: 1 },
      type: "baddie",
    },
    "baddie@5,13,1:1rpQ64": {
      config: { activated: false, startDirection: "right", which: "cyberman" },
      position: { x: 5, y: 13, z: 1 },
      type: "baddie",
    },
    "baddie@6,10,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 10, z: 1 },
      type: "baddie",
    },
    "baddie@6,11,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 11, z: 1 },
      type: "baddie",
    },
    "baddie@6,12,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 12, z: 1 },
      type: "baddie",
    },
    "baddie@6,13,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 13, z: 1 },
      type: "baddie",
    },
    "baddie@6,2,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 2, z: 1 },
      type: "baddie",
    },
    "baddie@6,3,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 3, z: 1 },
      type: "baddie",
    },
    "baddie@6,4,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 4, z: 1 },
      type: "baddie",
    },
    "baddie@6,5,1:2q6IfP": {
      config: { activated: false, startDirection: "left", which: "cyberman" },
      position: { x: 6, y: 5, z: 1 },
      type: "baddie",
    },
    "deadlyBlock@0,10,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 0, y: 10, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@0,11,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 0, y: 11, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@0,12,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 0, y: 12, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@0,13,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 0, y: 13, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,1,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 11, y: 1, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,14,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 11, y: 14, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,2,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 11, y: 2, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,3,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 11, y: 3, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,4,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 11, y: 4, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,5,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 11, y: 5, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@11,9,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 11, y: 9, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,10,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 5, y: 10, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,11,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 5, y: 11, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,12,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 5, y: 12, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@5,13,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 5, y: 13, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,10,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 10, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,11,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 11, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,12,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 12, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,13,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 13, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,2,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 2, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,3,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 3, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,4,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 4, z: 0 },
      type: "deadlyBlock",
    },
    "deadlyBlock@6,5,0:2u1uHB": {
      config: { style: "toaster" },
      position: { x: 6, y: 5, z: 0 },
      type: "deadlyBlock",
    },
    "door@12,11,0:Z8uHEk": {
      config: { direction: "left", toRoom: "moonbase34" },
      position: { x: 12, y: 11, z: 0 },
      type: "door",
    },
    "door@2,16,0:11h9Mo": {
      config: { direction: "away", toRoom: "moonbase36" },
      position: { x: 2, y: 16, z: 0 },
      type: "door",
    },
    "door@8,0,0:5CIOF": {
      config: { direction: "towards", toRoom: "moonbase32" },
      position: { x: 8, y: 0, z: 0 },
      type: "door",
    },
    "wall@0,7,0:Z2oYlvx": {
      config: { side: "away", style: "coil" },
      position: { x: 0, y: 7, z: 0 },
      type: "wall",
    },
    "wall@1,7,0:Z2oYlvx": {
      config: { side: "away", style: "coil" },
      position: { x: 1, y: 7, z: 0 },
      type: "wall",
    },
    "wall@2,7,0:Z2oYlvx": {
      config: { side: "away", style: "coil" },
      position: { x: 2, y: 7, z: 0 },
      type: "wall",
    },
    "wall@3,7,0:Z2oYlvx": {
      config: { side: "away", style: "coil" },
      position: { x: 3, y: 7, z: 0 },
      type: "wall",
    },
    "wall@4,7,0:Z2oYlvx": {
      config: { side: "away", style: "coil" },
      position: { x: 4, y: 7, z: 0 },
      type: "wall",
    },
    "wall@5,0,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 0, z: 0 },
      type: "wall",
    },
    "wall@5,1,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 1, z: 0 },
      type: "wall",
    },
    "wall@5,2,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 2, z: 0 },
      type: "wall",
    },
    "wall@5,3,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 3, z: 0 },
      type: "wall",
    },
    "wall@5,4,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 4, z: 0 },
      type: "wall",
    },
    "wall@5,5,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 5, z: 0 },
      type: "wall",
    },
    "wall@5,6,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 6, z: 0 },
      type: "wall",
    },
    "wall@5,7,0:Z2oYlvx": {
      config: { side: "away", style: "coil" },
      position: { x: 5, y: 7, z: 0 },
      type: "wall",
    },
    "wall@5,7,0:ZcS5yT": {
      config: { side: "left", style: "coil" },
      position: { x: 5, y: 7, z: 0 },
      type: "wall",
    },
  },
  planet: "moonbase",
  size: { x: 12, y: 16 },
  walls: {
    away: [
      "window3",
      "window2",
      "none",
      "none",
      "window2",
      "window1",
      "window1",
      "coil",
      "window3",
      "window2",
      "coil",
      "window1",
    ],
    left: [
      "window2",
      "window1",
      "coil",
      "window3",
      "window2",
      "coil",
      "window2",
      "window1",
      "window2",
      "coil",
      "window3",
      "none",
      "none",
      "window3",
      "coil",
      "window1",
    ],
  },
} satisfies RoomJson<"moonbase", OriginalCampaignRoomId>;
