#!/usr/bin/env node
/* Generate a groups json for a snapshots-only review, with no authoring step.
 *
 * A review of changed screenshot baselines needs no judgement: the groups are
 * the snapshot directories, the reading order is alphabetical, and the only
 * note worth having - what % of pixels changed - is computed by the page
 * itself. So this script replaces the authored json wherever the scope is
 * "just the snapshots", and its output feeds build.ts exactly as an authored
 * file would:
 *
 *   node snapshotGroups.ts --mode worktree > groups.json
 *   node snapshotGroups.ts --mode pr --base origin/main --head origin/topic --out groups.json
 *   node snapshotGroups.ts --mode commit --ref <sha> --glob 'e2e/*-snapshots'
 *
 * --glob (default 'e2e/*-snapshots') bounds which directories count as
 * snapshot baselines; it is matched against the leading directories of each
 * changed path, with * standing for one path segment.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

import { isImagePath } from "./src/imagePaths.ts";
import { type ReviewGroup, type ReviewItem } from "./src/ReviewPayload.ts";

const skillDir = dirname(fileURLToPath(import.meta.url));

const { values } = parseArgs({
  options: {
    mode: { type: "string" },
    ref: { type: "string" },
    base: { type: "string" },
    head: { type: "string" },
    glob: { type: "string", default: "e2e/*-snapshots" },
    out: { type: "string" },
  },
});

const { mode, ref, base, head, glob, out } = values;
if (
  mode === undefined ||
  (mode === "commit" && ref === undefined) ||
  (mode === "pr" && (base === undefined || head === undefined))
) {
  console.error(
    "snapshotGroups.ts --mode worktree|commit|pr [--ref <sha>] [--base <ref> --head <ref>] [--glob 'e2e/*-snapshots'] [--out <path>]",
  );
  process.exit(1);
}

/** the glob as a leading-directories test: * spans one path segment */
const globPattern = new RegExp(
  `^${glob
    .split("*")
    .map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("[^/]*")}/`,
);

const changedFilesArgs =
  mode === "worktree" ? ["worktree"]
  : mode === "commit" ? ["commit", ref ?? ""]
  : ["pr", base ?? "", head ?? ""];

const changed = execFileSync(join(skillDir, "changedFiles.sh"), changedFilesArgs, {
  encoding: "utf8",
});

type ChangedImage = { path: string; status: string };

const snapshots: ChangedImage[] = changed
  .split("\n")
  .filter((line) => line.includes("\t"))
  .map((line) => {
    const [status = "", path = ""] = line.split("\t");
    return { path, status: status.charAt(0) };
  })
  .filter(({ path }) => isImagePath(path) && globPattern.test(path))
  .sort((left, right) => left.path.localeCompare(right.path));

if (snapshots.length === 0) {
  console.error(`no changed snapshot baselines under ${glob}`);
  process.exit(1);
}

/** "e2e/roomSnapshots.spec.ts-snapshots/chromium-desktop" -> a readable title */
const titleOfDirectory = (directory: string): string => {
  const parts = directory.split("/");
  const snapshotsDir = parts.find((part) => part.endsWith("-snapshots"));
  if (snapshotsDir === undefined) {
    return directory;
  }
  const spec = snapshotsDir.replace(/(\.spec\.[jt]sx?)?-snapshots$/, "");
  const project = parts.slice(parts.indexOf(snapshotsDir) + 1).join("/");
  return project === "" ? spec : `${spec} — ${project}`;
};

const byDirectory = new Map<string, ReviewItem[]>();
for (const { path, status } of snapshots) {
  const directory = dirname(path);
  const existing = byDirectory.get(directory);
  const item: ReviewItem = { path, status };
  if (existing === undefined) {
    byDirectory.set(directory, [item]);
  } else {
    existing.push(item);
  }
}

const groups: ReviewGroup[] = [...byDirectory]
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([directory, items]) => ({
    title: titleOfDirectory(directory),
    blurb: `<code>${directory}</code>`,
    items,
  }));

const scope =
  mode === "worktree" ? "uncommitted baselines vs HEAD"
  : mode === "commit" ? `baselines changed by ${ref}`
  : `baselines changed by ${head} vs ${base}`;

const authored = {
  meta: {
    title: `snapshot changes — ${snapshots.length} baseline${snapshots.length === 1 ? "" : "s"}`,
    headerTitle: "snapshot review",
    eyebrow: "snapshot review",
    lede:
      `${scope}. Every image opens into a compare viewer - swipe, diff and ` +
      `overlay any pair of its versions; the %-changed line under each file ` +
      `is computed in this page.`,
    footer: "generated by snapshotGroups.ts - no authored notes in this review",
  },
  groups,
};

const json = JSON.stringify(authored, null, 2);
if (out === undefined) {
  console.log(json);
} else {
  writeFileSync(out, json, "utf8");
  console.error(`wrote ${out}`);
}
console.error(`${snapshots.length} baselines in ${groups.length} groups`);
