import { Color } from "pixi.js";

import { type SpritesheetMetadata } from "../../src/sprites/spritesheet/spritesheetData/spritesheetMetaData";
import { blockStackSpritesheetMeta } from "./blockStackSpritesheetMeta";

export type DebugPaletteColourName = "cyan" | "red";

const {
  playable,
  itemRenderExtents,
  showFloorOverDraw,
  teleporterEffectBlackPoint,
} = blockStackSpritesheetMeta;

/**
 * Cheats-only spritesheet for debugging rendering. Every sprite is flattened to
 * a flat ZX Spectrum block colour with its texture id written across it, so
 * sprite identity and placement read straight off the screen. The committed
 * image gfx/spritesDebug.webp is generated by scripts/debugSpritesheet.ts and
 * loaded like any other sheet. This palette (used only for hud tints, effect
 * outlines and floating text) is a plain red/cyan pair.
 */
export const debugSpritesheetMeta: SpritesheetMetadata<
  DebugPaletteColourName,
  "Debug",
  false
> = {
  name: "Debug",
  palette: {
    red: new Color(0xff_00_00),
    cyan: new Color(0x00_ff_ff),
  },
  playable,
  itemRenderExtents,
  // every sprite is present as its own labelled block: no copyFrom aliasing and
  // no dropped textures
  overrides: undefined,
  missedTextures: undefined,
  swops: undefined,
  effectColours: {
    head: "cyan",
    heels: "red",
    left: "cyan",
    right: "red",
    invulnerable: "cyan",
    dimText: "red",
    carry: "cyan",
    outline: "red",
  },
  floatingTextGradient: ["red", "cyan"],
  buttonColours: {
    jump: "cyan",
    fire: "cyan",
    carry: "cyan",
    carryAndJump: "cyan",
    menu: "red",
    map: "red",
    rotateClockwise: "red",
    rotateAnticlockwise: "red",
  },
  supportsUncolourised: false,
  debug: true,
  showFloorOverDraw,
  teleporterEffectBlackPoint,
};
