/**
 * Tailwind v4 dropped the `safelist` config option. The sprite plugin generates
 * a `texture-*` utility for every sprite, but some are referenced by class names
 * computed at runtime (hud chars in markdown, the playable head/heels animations
 * shown with `selectedMenuItem:`/`activated:` variants) that v4's source scanner
 * can't see. This regenerates the v3 `safelist` as `@source inline(...)` lines so
 * those classes are always kept. Run via `pnpm gen:tailwindSafelist`.
 */
import { writeFileSync } from "node:fs";

import { sanitiseForClassName } from "../src/game/components/tailwindSprites/SanitiseForClassName";
import { makeSpritesheetData } from "../src/sprites/spritesheet/spritesheetData/makeSpritesheetData";
import { spritesheetMetas } from "../src/sprites/spritesheet/spritesheetData/spritesheetMetaData";

const full = makeSpritesheetData({ playable: { head: {}, heels: {} } });

const classes = new Set<string>();

// pattern: texture-hud_char_*  and  texture-(head|heels)_(walking|standing|blinking)_*
for (const id of Object.keys(full.frames)) {
  const cls = `texture-${sanitiseForClassName(id)}`;
  if (
    /^texture-hud_char_/.test(cls) ||
    /^texture-(head|heels)_(walking|standing|blinking)_/.test(cls)
  ) {
    classes.add(cls);
  }
}

// pattern: texture-animated-(head|heels)_(walking|idle)_* with selectedMenuItem/activated variants
const animationNames = new Set<string>();
// the playable (head/heels) animations live on the `full` sheet (built with the
// `playable` param); other animations come from the per-sheet metas.
for (const name of Object.keys(full.animations ?? {})) {
  animationNames.add(name);
}
for (const meta of Object.values(spritesheetMetas)) {
  const sheet = makeSpritesheetData(meta);
  for (const name of Object.keys(sheet.animations ?? {})) {
    animationNames.add(name);
  }
}
for (const name of animationNames) {
  const base = `texture-animated-${sanitiseForClassName(name)}`;
  if (/^texture-animated-(head|heels)_(walking|idle)_/.test(base)) {
    classes.add(base);
    classes.add(`selectedMenuItem:${base}`);
    classes.add(`activated:${base}`);
  }
}

const lines = [
  "/* GENERATED by scripts/genTailwindSafelist.ts - do not edit. */",
  ...[...classes].sort().map((c) => `@source inline("${c}");`),
  "",
];
writeFileSync("src/_generated/tailwindSafelist.css", lines.join("\n"));
console.log(`wrote ${classes.size} safelisted classes`);
