import type { MarkdownPageName } from "../../../../manual/pages";

export type DialogId =
  | "about"
  | "communityGames"
  | "controlOptions"
  | "crowns"
  | "displayOptions"
  | "emulatedResolution"
  | "errorCaught"
  | "hold"
  | "inputPreset"
  | "installGuide"
  | "mainMenu"
  | "map"
  | "markdown/inline"
  | "modernisationOptions"
  | "offerReincarnation"
  | "proclaimEmperor"
  | "quitGameConfirm"
  | "readTheManual"
  | "reincarnatedRestart"
  | "score"
  | "sound"
  | "sureWantEditor"
  | "whichGame"
  | `markdown/${MarkdownPageName}`;
