// Auto-generated by sfxdex. Do not edit manually.

import activateSoundUrl from "./sfx/activate.opus";
import ballHitSoundUrl from "./sfx/ballHit.opus";
import blacktoothSoundUrl from "./sfx/blacktooth.opus";
import bookworldSoundUrl from "./sfx/bookworld.opus";
import bubbleRobotLoopSoundUrl from "./sfx/bubbleRobotLoop.opus";
import buttonOffSoundUrl from "./sfx/buttonOff.opus";
import buttonOnSoundUrl from "./sfx/buttonOn.opus";
import carrySoundUrl from "./sfx/carry.opus";
import collectedItemSoundUrl from "./sfx/collectedItem.opus";
import collectedRabbitSoundUrl from "./sfx/collectedRabbit.opus";
import conveyorEndSoundUrl from "./sfx/conveyorEnd.opus";
import conveyorLoopSoundUrl from "./sfx/conveyorLoop.opus";
import conveyorStartSoundUrl from "./sfx/conveyorStart.opus";
import crownSparkleSoundUrl from "./sfx/crownSparkle.opus";
import deactivateSoundUrl from "./sfx/deactivate.opus";
import destroySoundUrl from "./sfx/destroy.opus";
import detectSoundUrl from "./sfx/detect.opus";
import doorSoundUrl from "./sfx/door.opus";
import doughnutSplatSoundUrl from "./sfx/doughnutSplat.opus";
import drumSoundUrl from "./sfx/drum.opus";
import egyptusSoundUrl from "./sfx/egyptus.opus";
import elephantHootSoundUrl from "./sfx/elephantHoot.opus";
import emitSoundUrl from "./sfx/emit.opus";
import fallSoundUrl from "./sfx/fall.opus";
import fanfareSoundUrl from "./sfx/fanfare.opus";
import glassClinkSoundUrl from "./sfx/glassClink.opus";
import glideSoundUrl from "./sfx/glide.opus";
import glitchRobotSoundUrl from "./sfx/glitchRobot.opus";
import headAccentSoundUrl from "./sfx/headAccent.opus";
import headJumpingSoundUrl from "./sfx/headJumping.opus";
import headJumpStartSoundUrl from "./sfx/headJumpStart.opus";
import headOverHeelsAccentSoundUrl from "./sfx/headOverHeelsAccent.opus";
import headWalkSoundUrl from "./sfx/headWalk.opus";
import heavyScrapeSoundUrl from "./sfx/heavyScrape.opus";
import heelsAccentSoundUrl from "./sfx/heelsAccent.opus";
import heelsJumpingSoundUrl from "./sfx/heelsJumping.opus";
import heelsJumpStartSoundUrl from "./sfx/heelsJumpStart.opus";
import heelsWalkSoundUrl from "./sfx/heelsWalk.opus";
import helicopterSoundUrl from "./sfx/helicopter.opus";
import hooterSoundUrl from "./sfx/hooter.opus";
import hushPuppyVanishSoundUrl from "./sfx/hushPuppyVanish.opus";
import iceSlideSoundUrl from "./sfx/iceSlide.opus";
import introSoundUrl from "./sfx/intro.opus";
import jetpackLoopSoundUrl from "./sfx/jetpackLoop.opus";
import jetpackTurnaroundSoundUrl from "./sfx/jetpackTurnaround.opus";
import loopSoundUrl from "./sfx/loop.opus";
import lowerSmallMotorLoopSoundUrl from "./sfx/lowerSmallMotorLoop.opus";
import lowHumSoundUrl from "./sfx/lowHum.opus";
import marketSoundUrl from "./sfx/market.opus";
import menuSofterSoundUrl from "./sfx/menuSofter.opus";
import metalClangSoundUrl from "./sfx/metalClang.opus";
import mojoLoopSoundUrl from "./sfx/mojoLoop.opus";
import mojoTurnSoundUrl from "./sfx/mojoTurn.opus";
import monkeyTurnSoundUrl from "./sfx/monkeyTurn.opus";
import moonbaseSoundUrl from "./sfx/moonbase.opus";
import moonbaseDoorSoundUrl from "./sfx/moonbaseDoor.opus";
import penitentiarySoundUrl from "./sfx/penitentiary.opus";
import robotWhirLoopSoundUrl from "./sfx/robotWhirLoop.opus";
import rollingBallLoopSoundUrl from "./sfx/rollingBallLoop.opus";
import safariSoundUrl from "./sfx/safari.opus";
import scrapeSoundUrl from "./sfx/scrape.opus";
import scrollOpenSoundUrl from "./sfx/scrollOpen.opus";
import servoLoopSoundUrl from "./sfx/servoLoop.opus";
import servoStartSoundUrl from "./sfx/servoStart.opus";
import servoStopSoundUrl from "./sfx/servoStop.opus";
import setting0SoundUrl from "./sfx/setting0.opus";
import setting1SoundUrl from "./sfx/setting1.opus";
import setting2SoundUrl from "./sfx/setting2.opus";
import setting3SoundUrl from "./sfx/setting3.opus";
import softBumpSoundUrl from "./sfx/softBump.opus";
import springBoingSoundUrl from "./sfx/springBoing.opus";
import switchClickSoundUrl from "./sfx/switchClick.opus";
import teleportInSoundUrl from "./sfx/teleportIn.opus";
import teleportOutSoundUrl from "./sfx/teleportOut.opus";
import teleportWarningSirenSoundUrl from "./sfx/teleportWarningSiren.opus";
import toasterPopUpSoundUrl from "./sfx/toasterPopUp.opus";
import toasterPushDownSoundUrl from "./sfx/toasterPushDown.opus";
import uhOhSoundUrl from "./sfx/uhOh.opus";

export { activateSoundUrl };
export { ballHitSoundUrl };
export { blacktoothSoundUrl };
export { bookworldSoundUrl };
export { bubbleRobotLoopSoundUrl };
export { buttonOffSoundUrl };
export { buttonOnSoundUrl };
export { carrySoundUrl };
export { collectedItemSoundUrl };
export { collectedRabbitSoundUrl };
export { conveyorEndSoundUrl };
export { conveyorLoopSoundUrl };
export { conveyorStartSoundUrl };
export { crownSparkleSoundUrl };
export { deactivateSoundUrl };
export { destroySoundUrl };
export { detectSoundUrl };
export { doorSoundUrl };
export { doughnutSplatSoundUrl };
export { drumSoundUrl };
export { egyptusSoundUrl };
export { elephantHootSoundUrl };
export { emitSoundUrl };
export { fallSoundUrl };
export { fanfareSoundUrl };
export { glassClinkSoundUrl };
export { glideSoundUrl };
export { glitchRobotSoundUrl };
export { headAccentSoundUrl };
export { headJumpingSoundUrl };
export { headJumpStartSoundUrl };
export { headOverHeelsAccentSoundUrl };
export { headWalkSoundUrl };
export { heavyScrapeSoundUrl };
export { heelsAccentSoundUrl };
export { heelsJumpingSoundUrl };
export { heelsJumpStartSoundUrl };
export { heelsWalkSoundUrl };
export { helicopterSoundUrl };
export { hooterSoundUrl };
export { hushPuppyVanishSoundUrl };
export { iceSlideSoundUrl };
export { introSoundUrl };
export { jetpackLoopSoundUrl };
export { jetpackTurnaroundSoundUrl };
export { loopSoundUrl };
export { lowerSmallMotorLoopSoundUrl };
export { lowHumSoundUrl };
export { marketSoundUrl };
export { menuSofterSoundUrl };
export { metalClangSoundUrl };
export { mojoLoopSoundUrl };
export { mojoTurnSoundUrl };
export { monkeyTurnSoundUrl };
export { moonbaseSoundUrl };
export { moonbaseDoorSoundUrl };
export { penitentiarySoundUrl };
export { robotWhirLoopSoundUrl };
export { rollingBallLoopSoundUrl };
export { safariSoundUrl };
export { scrapeSoundUrl };
export { scrollOpenSoundUrl };
export { servoLoopSoundUrl };
export { servoStartSoundUrl };
export { servoStopSoundUrl };
export { setting0SoundUrl };
export { setting1SoundUrl };
export { setting2SoundUrl };
export { setting3SoundUrl };
export { softBumpSoundUrl };
export { springBoingSoundUrl };
export { switchClickSoundUrl };
export { teleportInSoundUrl };
export { teleportOutSoundUrl };
export { teleportWarningSirenSoundUrl };
export { toasterPopUpSoundUrl };
export { toasterPushDownSoundUrl };
export { uhOhSoundUrl };

export const exportedSfxUrls = {
  activate: activateSoundUrl,
  ballHit: ballHitSoundUrl,
  blacktooth: blacktoothSoundUrl,
  bookworld: bookworldSoundUrl,
  bubbleRobotLoop: bubbleRobotLoopSoundUrl,
  buttonOff: buttonOffSoundUrl,
  buttonOn: buttonOnSoundUrl,
  carry: carrySoundUrl,
  collectedItem: collectedItemSoundUrl,
  collectedRabbit: collectedRabbitSoundUrl,
  conveyorEnd: conveyorEndSoundUrl,
  conveyorLoop: conveyorLoopSoundUrl,
  conveyorStart: conveyorStartSoundUrl,
  crownSparkle: crownSparkleSoundUrl,
  deactivate: deactivateSoundUrl,
  destroy: destroySoundUrl,
  detect: detectSoundUrl,
  door: doorSoundUrl,
  doughnutSplat: doughnutSplatSoundUrl,
  drum: drumSoundUrl,
  egyptus: egyptusSoundUrl,
  elephantHoot: elephantHootSoundUrl,
  emit: emitSoundUrl,
  fall: fallSoundUrl,
  fanfare: fanfareSoundUrl,
  glassClink: glassClinkSoundUrl,
  glide: glideSoundUrl,
  glitchRobot: glitchRobotSoundUrl,
  headAccent: headAccentSoundUrl,
  headJumping: headJumpingSoundUrl,
  headJumpStart: headJumpStartSoundUrl,
  headOverHeelsAccent: headOverHeelsAccentSoundUrl,
  headWalk: headWalkSoundUrl,
  heavyScrape: heavyScrapeSoundUrl,
  heelsAccent: heelsAccentSoundUrl,
  heelsJumping: heelsJumpingSoundUrl,
  heelsJumpStart: heelsJumpStartSoundUrl,
  heelsWalk: heelsWalkSoundUrl,
  helicopter: helicopterSoundUrl,
  hooter: hooterSoundUrl,
  hushPuppyVanish: hushPuppyVanishSoundUrl,
  iceSlide: iceSlideSoundUrl,
  intro: introSoundUrl,
  jetpackLoop: jetpackLoopSoundUrl,
  jetpackTurnaround: jetpackTurnaroundSoundUrl,
  loop: loopSoundUrl,
  lowerSmallMotorLoop: lowerSmallMotorLoopSoundUrl,
  lowHum: lowHumSoundUrl,
  market: marketSoundUrl,
  menuSofter: menuSofterSoundUrl,
  metalClang: metalClangSoundUrl,
  mojoLoop: mojoLoopSoundUrl,
  mojoTurn: mojoTurnSoundUrl,
  monkeyTurn: monkeyTurnSoundUrl,
  moonbase: moonbaseSoundUrl,
  moonbaseDoor: moonbaseDoorSoundUrl,
  penitentiary: penitentiarySoundUrl,
  robotWhirLoop: robotWhirLoopSoundUrl,
  rollingBallLoop: rollingBallLoopSoundUrl,
  safari: safariSoundUrl,
  scrape: scrapeSoundUrl,
  scrollOpen: scrollOpenSoundUrl,
  servoLoop: servoLoopSoundUrl,
  servoStart: servoStartSoundUrl,
  servoStop: servoStopSoundUrl,
  setting0: setting0SoundUrl,
  setting1: setting1SoundUrl,
  setting2: setting2SoundUrl,
  setting3: setting3SoundUrl,
  softBump: softBumpSoundUrl,
  springBoing: springBoingSoundUrl,
  switchClick: switchClickSoundUrl,
  teleportIn: teleportInSoundUrl,
  teleportOut: teleportOutSoundUrl,
  teleportWarningSiren: teleportWarningSirenSoundUrl,
  toasterPopUp: toasterPopUpSoundUrl,
  toasterPushDown: toasterPushDownSoundUrl,
  uhOh: uhOhSoundUrl,
};

export type ExportedSoundId = keyof typeof exportedSfxUrls;

export const isSoundId = (id: string): id is ExportedSoundId =>
  id in exportedSfxUrls;

export const sfxLooping = new Set<ExportedSoundId>([
  "bubbleRobotLoop",
  "conveyorLoop",
  "fall",
  "glide",
  "glitchRobot",
  "headJumping",
  "headWalk",
  "heelsJumping",
  "heelsWalk",
  "helicopter",
  "iceSlide",
  "intro",
  "jetpackLoop",
  "loop",
  "lowHum",
  "mojoLoop",
  "robotWhirLoop",
  "scrape",
  "servoLoop",
  "teleportWarningSiren",
] as ExportedSoundId[]);

export const sfxLoopPadMs: Partial<Record<ExportedSoundId, number>> = {
  bubbleRobotLoop: 20,
  conveyorLoop: 20,
  fall: 20,
  glide: 20,
  glitchRobot: 20,
  headJumping: 20,
  headWalk: 20,
  heelsJumping: 20,
  heelsWalk: 20,
  helicopter: 20,
  iceSlide: 20,
  intro: 20,
  jetpackLoop: 20,
  loop: 20,
  lowHum: 20,
  mojoLoop: 20,
  robotWhirLoop: 20,
  scrape: 20,
  servoLoop: 20,
  teleportWarningSiren: 20,
};
