import { BitmapText, type Color } from "pixi.js";

import { type PokeableNumber } from "../../../model/ItemStateMap";
import { paletteBlockstack } from "../../../sprites/palette/spritesheetPalette";
import { hudCharTextureSize } from "../../../sprites/spritesheet/spritesheetData/textureSizes";
import { OutlineFilter } from "../filters/OutlineFilter";

/**
 * The HUD web font, declared as `@font-face { font-family: "HeadOverHeels" }` in
 * `src/index.css` and generated by `pnpm gen:font`. Pixi builds a dynamic bitmap
 * font from it on first use.
 */
const hudFontFamily = "HeadOverHeels";

/**
 * Horizontally centred, with the vertical origin at the text's baseline - this
 * matches the sprite-font renderer this replaces, whose origin was the character
 * baseline (upper-case/digit cells sat with their bottom on the origin). The
 * font has an 8px ascender and a 2px descender per 8px em, so the baseline sits
 * `8 / (8 + 2)` of the way down the line box.
 */
const hudTextAnchor = { x: 0.5, y: 0.8 };

/**
 * The printable form of a HUD value: `"infinite"` renders as nothing (so the
 * lives/doughnuts count is blank when infinite lives are on), everything else as
 * its own string.
 */
export const abilityText = (value: PokeableNumber | string): string =>
  typeof value === "string" ?
    value === "infinite" ?
      ""
    : value
  : value.toString();

export type CreateHudTextOptions = {
  text?: PokeableNumber | string;
  colour?: Color;
  outline?: boolean;
  doubleHeight?: boolean;
  doubleWidth?: boolean;
  x?: number;
  y?: number;
  label?: string;
};

/**
 * Creates a {@link BitmapText} rendering game-engine HUD text with the
 * `"HeadOverHeels"` web font. Anchored horizontally centred with its origin on
 * the text baseline, so call sites position it by the baseline.
 */
export const createHudText = ({
  text = "",
  colour,
  outline = false,
  doubleHeight = false,
  doubleWidth = false,
  x = 0,
  y = 0,
  label = "hudText",
}: CreateHudTextOptions): BitmapText => {
  const bitmapText = new BitmapText({
    text: abilityText(text),
    style: {
      fontFamily: hudFontFamily,
      fontSize: hudCharTextureSize.h,
    },
    anchor: hudTextAnchor,
    label,
    x,
    y,
  });

  // the font has a real double-height variation axis (HGHT), but Pixi's
  // TextStyle can't select variation settings - scaling is visually identical
  // and stays crisp because gameMain sets the default texture scale mode to
  // "nearest":
  if (doubleWidth) {
    bitmapText.scale.x = 2;
  }
  if (doubleHeight) {
    bitmapText.scale.y = 2;
  }

  if (colour !== undefined) {
    bitmapText.tint = colour;
  }

  if (outline) {
    bitmapText.filters = new OutlineFilter({
      color: paletteBlockstack.pureBlack,
      width: 1,
      clipToViewport: false,
    });
  }

  return bitmapText;
};
