import { CanvasSource, type Color, Sprite, Texture } from "pixi.js";

import { type PokeableNumber } from "../../../model/ItemStateMap";
import {
  hudCharTextureSize,
  hudLowercaseCharTextureSize,
} from "../../../sprites/spritesheet/spritesheetData/textureSizes";
import { outlineFilters } from "../filters/OutlineFilter";

/**
 * The HUD web font, declared as `@font-face { font-family: "HeadOverHeels" }` in
 * `src/index.css` and generated by `pnpm gen:font`. It is a pixel font built
 * from axis-aligned rectangles on an integer 8px-per-em grid with integer
 * advance widths, so canvas rasterisation at 8px is pixel-exact.
 */
const hudFont = `${hudCharTextureSize.h}px "HeadOverHeels"`;

/** 8px ascender + 2px descender per 8px em */
const textureHeight = hudLowercaseCharTextureSize.h;
const baselineY = hudCharTextureSize.h;

/**
 * Horizontally centred, with the vertical origin at the text's baseline - this
 * matches the sprite-font renderer this replaces, whose origin was the
 * character baseline (upper-case/digit cells sat with their bottom on the
 * origin).
 */
const hudTextAnchor = { x: 0.5, y: baselineY / textureHeight };

/** same ink test as the font generator (scripts/genFont.ts) */
const inkAlphaThreshold = 128;

let fontLoadPromise: Promise<void> | undefined;
/**
 * Resolves when the HUD font is genuinely usable by canvas 2d. A plain
 * `document.fonts.load` is not enough at boot: module js runs without waiting
 * for stylesheets, so the css `@font-face` may not be in the CSSOM yet - in
 * that state `fonts.load` matches nothing and resolves immediately with an
 * empty array. Poll until the face exists, then await its load.
 */
export const loadHudFont = (): Promise<void> =>
  (fontLoadPromise ??= (async () => {
    while ((await document.fonts.load(hudFont)).length === 0) {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  })());

/**
 * The printable form of a HUD value: `"infinite"` renders as nothing (so the
 * lives/doughnuts count is blank when infinite lives are on), everything else
 * as its own string.
 */
export const abilityText = (value: PokeableNumber | string): string =>
  typeof value === "string" ?
    value === "infinite" ?
      ""
    : value
  : value.toString();

// a DOM canvas (not OffscreenCanvas): a main-thread OffscreenCanvas does not
// reliably see fonts loaded into document.fonts in Chromium, and would
// silently rasterise with a fallback font. A detached canvas element does.
const hudTextCanvas = (width: number, height: number): HTMLCanvasElement => {
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  return canvas;
};

const context2d = (canvas: HTMLCanvasElement) => {
  const maybeContext = canvas.getContext("2d", { willReadFrequently: true });
  if (import.meta.env.DEV && maybeContext === null) {
    throw new Error("could not get a 2d context for hud text rasterisation");
  }
  const context = maybeContext!;
  // the default ("auto") lets the browser grid-fit (hint) the unhinted pixel
  // font at 8px, which fattens glyphs with diagonal edges (eg ⚡/🛡/♨) by 1-2px
  // per row; geometricPrecision renders the true contours, which are already
  // on the pixel grid and need no fitting
  context.textRendering = "geometricPrecision";
  return context;
};

let measureContext: CanvasRenderingContext2D | undefined;
const measureHudTextWidth = (str: string): number => {
  if (measureContext === undefined) {
    measureContext = context2d(hudTextCanvas(1, 1));
  }
  measureContext.font = hudFont;
  return Math.round(measureContext.measureText(str).width);
};

/**
 * Rasterises a whole string to a texture with canvas 2d. The font's glyphs are
 * rectangles on the integer pixel grid with integer advances, so the output is
 * pixel-identical to the original sprite-font art; the alpha threshold only
 * guards against browser antialiasing differences at the edges. The ink is
 * white so the sprite's tint colours it.
 *
 * `gameMain` awaits {@link loadHudFont} before the first render so this
 * normally never sees a fallback font; {@link HudText} additionally
 * re-rasterises when the font arrives in case an instance was created before
 * it loaded (eg in the editor, which has no font gate).
 */
const rasteriseHudText = (str: string): Texture => {
  const width = measureHudTextWidth(str);
  if (width === 0) {
    return Texture.EMPTY;
  }

  const canvas = hudTextCanvas(width, textureHeight);
  const context = context2d(canvas);
  context.font = hudFont;
  context.textBaseline = "alphabetic";
  context.fillStyle = "#ffffff";
  context.fillText(str, 0, baselineY);

  const imageData = context.getImageData(0, 0, width, textureHeight);
  const { data } = imageData;
  for (let i = 3; i < data.length; i += 4) {
    data[i] = data[i] >= inkAlphaThreshold ? 255 : 0;
  }
  context.putImageData(imageData, 0, 0);

  return new Texture({ source: new CanvasSource({ resource: canvas }) });
};

export type HudTextOptions = {
  text?: PokeableNumber | string;
  colour?: Color;
  outline?: boolean;
  doubleHeight?: boolean;
  doubleWidth?: boolean;
  x?: number;
  y?: number;
  label?: string;
};

/**
 * Game-engine HUD text: each string is rasterised to its own small texture and
 * shown as a single sprite. Strings change rarely once created (lives counts,
 * button glyphs, floating text lines), so re-rasterising on change is cheap -
 * and rendering whole strings needs none of Pixi's text machinery in the
 * bundle. Anchored horizontally centred with the origin on the text baseline,
 * so call sites position it by the baseline.
 */
export class HudText extends Sprite {
  #currentText: string;

  constructor({
    text = "",
    colour,
    outline = false,
    doubleHeight = false,
    doubleWidth = false,
    x = 0,
    y = 0,
    label = "hudText",
  }: HudTextOptions) {
    const str = abilityText(text);
    super({
      texture: rasteriseHudText(str),
      anchor: hudTextAnchor,
      label,
      x,
      y,
    });
    this.#currentText = str;

    // the font has a real double-height variation axis (HGHT), but for a font
    // of axis-aligned rectangles scaling is pixel-identical and stays crisp
    // because gameMain sets the default texture scale mode to "nearest":
    if (doubleWidth) {
      this.scale.x = 2;
    }
    if (doubleHeight) {
      this.scale.y = 2;
    }

    if (colour !== undefined) {
      this.tint = colour;
    }

    if (outline) {
      // the shared filter follows the game's global upscale, so the outline is
      // always 1px on the game's own pixel grid. (The old sprite-font renderer
      // used width 1 with clipToViewport false because it applied the filter
      // while baking off-screen at 1:1 game resolution; this filter runs live
      // on-screen, where filter pixels are upscaled screen pixels.)
      this.filters = outlineFilters.pureBlack;
    }

    // constructed before the font loaded: the texture just rasterised shows a
    // fallback font - redo it (for the current text at that time) once the
    // real font is available:
    if (!document.fonts.check(hudFont)) {
      loadHudFont().then(() => {
        if (!this.destroyed) {
          this.#replaceTexture(rasteriseHudText(this.#currentText));
        }
      });
    }
  }

  #replaceTexture(newTexture: Texture) {
    const oldTexture = this.texture;
    this.texture = newTexture;
    if (oldTexture !== Texture.EMPTY) {
      oldTexture.destroy(true);
    }
  }

  get text(): string {
    return this.#currentText;
  }

  set text(value: PokeableNumber | string) {
    const str = abilityText(value);
    if (str === this.#currentText) {
      return;
    }
    this.#replaceTexture(rasteriseHudText(str));
    this.#currentText = str;
  }

  override destroy(): void {
    // guard against double-destroy: eg the fps renderer's HudText is destroyed
    // both by the hud container's children cascade and by FpsRenderer.destroy
    if (this.destroyed) {
      return;
    }
    const { texture } = this;
    super.destroy();
    if (texture !== Texture.EMPTY) {
      texture.destroy(true);
    }
  }
}
