import {
  CanvasSource,
  Color,
  Container,
  Rectangle,
  type Renderer,
  Sprite,
  Texture,
} from "pixi.js";

import { type PokeableNumber } from "../../../model/ItemStateMap";
import { paletteBlockstack } from "../../../sprites/palette/spritesheetPalette";
import {
  hudCharTextureSize,
  hudLowercaseCharTextureSize,
} from "../../../sprites/spritesheet/spritesheetData/textureSizes";
import { renderContainerToTexture } from "../../../utils/pixi/renderContainerToSprite";
import { alphaThresholdFilter } from "../filters/alphaThresholdFilter";
import { OutlineFilter } from "../filters/OutlineFilter";
import {
  uiFontFamilies,
  type UiFontVariant,
  uiFontVariantAtResolution,
} from "./uiFont";

/**
 * The HUD web font at the size text is laid out in, generated by `pnpm
 * gen:font`. The base variant is a pixel font built from axis-aligned
 * rectangles on an integer 8px-per-em grid, so rasterisation at 8px is
 * pixel-exact; the smooth variant traces the same glyphs as curves, so it
 * gains detail when rasterised into a backing store larger than 8px per em.
 * Both variants share every advance width, so a string occupies the same
 * logical space whichever is drawn.
 */
const hudFont = (variant: UiFontVariant) =>
  `${hudCharTextureSize.h}px "${uiFontFamilies[variant]}"`;

/** 8px ascender + 2px descender per 8px em */
const textureHeight = hudLowercaseCharTextureSize.h;
const baselineY = hudCharTextureSize.h;

const printableString = (input: PokeableNumber | string): string => {
  return (
    typeof input === "string" ?
      (
        input === "infinite" // special case so that nothing shows on the UI for lives when infinite lives/doughnuts is on
      ) ?
        ""
      : input
    : input.toString()
  );
};

const white: Color = new Color(0xff_ff_ff);
const flashDurationMs = 100;

// a DOM canvas (not OffscreenCanvas): a main-thread OffscreenCanvas does not
// reliably see fonts loaded into document.fonts in Chromium, and would
// silently rasterise with a fallback font. A detached canvas element does.
const hudTextCanvas = (width: number, height: number): HTMLCanvasElement => {
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  return canvas;
};

const context2d = (canvas: HTMLCanvasElement) => {
  const maybeContext = canvas.getContext("2d", { willReadFrequently: true });
  if (import.meta.env.DEV && maybeContext === null) {
    throw new Error("could not get a 2d context for hud text rasterisation");
  }
  const context = maybeContext!;
  // the default ("auto") lets the browser grid-fit (hint) the unhinted pixel
  // font at 8px, which fattens glyphs with diagonal edges (eg ⚡/🛡/♨) by 1-2px
  // per row; geometricPrecision renders the true contours, which are already
  // on the pixel grid and need no fitting
  context.textRendering = "geometricPrecision";
  return context;
};

let measureContext: CanvasRenderingContext2D | undefined;
const measureHudTextWidth = (str: string, variant: UiFontVariant): number => {
  if (measureContext === undefined) {
    measureContext = context2d(hudTextCanvas(1, 1));
  }
  measureContext.font = hudFont(variant);
  return Math.round(measureContext.measureText(str).width);
};

/**
 * Rasterises a whole string's ink to a texture with canvas 2d, keeping whatever
 * antialiasing the browser produces at the glyph edges - {@link
 * alphaThresholdFilter} binarises it to a crisp pixel result later, on the GPU,
 * while the text is baked. The ink is white so the container's tint colours it.
 *
 * The canvas is `resolution` times the texture's logical size and the drawing
 * is scaled to match, so the ink keeps its position and size in logical
 * (8px-em) coordinates however dense its backing store is.
 *
 * The font family must already be registered, or canvas 2d silently draws with
 * a fallback font; the {@link TextContainer} constructor throws if it is not.
 */
const rasteriseInk = (
  str: string,
  variant: UiFontVariant,
  resolution: number,
): Texture => {
  const width = measureHudTextWidth(str, variant);
  if (width === 0) {
    return Texture.EMPTY;
  }

  const canvas = hudTextCanvas(width * resolution, textureHeight * resolution);
  const context = context2d(canvas);
  context.scale(resolution, resolution);
  context.font = hudFont(variant);
  context.textBaseline = "alphabetic";
  context.fillStyle = "#ffffff";
  context.fillText(str, 0, baselineY);

  return new Texture({
    source: new CanvasSource({ resource: canvas, resolution }),
  });
};

export type TextContainerOptions = {
  pixiRenderer: Renderer;
  /**
   * backing-store scale for the text's textures - pass the same factor the
   * sprites alongside it are baked at, so the text carries as much detail as
   * they do
   */
  resolution: number;
  doubleHeight?: boolean;
  doubleWidth?: boolean;
  outline?: boolean;
  label?: string;
  x?: number;
  y?: number;
  colour?: Color;
  flashColour?: Color;
  text?: number | string;
};

export class TextContainer extends Container {
  #pixiRenderer: Renderer;
  #currentText = "";
  #renderCacheSprite: Sprite;
  #inkSprite: Sprite;
  #renderToCacheContainer: Container<Sprite>;
  #heightMult: number;
  #widthMult: number;
  #resolution: number;
  #fontVariant: UiFontVariant;
  #colour: Color;
  #flashColour: Color | undefined;
  #flashTimeout: ReturnType<typeof setTimeout> | undefined;

  constructor({
    pixiRenderer,
    resolution,
    doubleHeight = false,
    doubleWidth = false,
    outline = false,
    label = "text",
    x,
    y,
    colour,
    flashColour,
    text,
  }: TextContainerOptions) {
    super({ label, x, y, tint: colour });

    this.#resolution = resolution;
    this.#fontVariant = uiFontVariantAtResolution(resolution);

    // rasterising happens synchronously via canvas fillText, which silently
    // falls back to a system font if the family is not registered yet. Callers
    // must await ensureUiFontLoaded() for this resolution's variant before
    // constructing text - not doing so is a bug.
    if (!document.fonts.check(hudFont(this.#fontVariant))) {
      throw new Error(
        `TextContainer created before the "${this.#fontVariant}" hud font was loaded - await ensureUiFontLoaded("${this.#fontVariant}") first`,
      );
    }

    this.#colour = colour ?? white;
    this.#flashColour = flashColour;

    this.#pixiRenderer = pixiRenderer;
    this.#heightMult = doubleHeight ? 2 : 1;
    this.#widthMult = doubleWidth ? 2 : 1;

    this.#renderCacheSprite = new Sprite();
    this.#renderCacheSprite.y = -(
      hudCharTextureSize.h * this.#heightMult +
      // an extra -1 to compensate for padding for outline:
      1
    );
    this.addChild(this.#renderCacheSprite);

    this.#renderToCacheContainer = new Container<Sprite>();
    this.addChild(this.#renderToCacheContainer);

    this.#inkSprite = new Sprite();
    this.#inkSprite.scale = {
      x: this.#widthMult,
      y: this.#heightMult,
    };
    // threshold first (binarise the browser's text antialiasing to a crisp
    // pixel result), then draw the outline around the crisp ink. Both run while
    // the text is baked off-screen into a cache texture.
    this.#inkSprite.filters =
      outline ?
        [
          alphaThresholdFilter,
          new OutlineFilter({
            color: paletteBlockstack.pureBlack,
            width: 1,
            // text is baked off-screen into a cache texture, so the outline
            // must not be clipped to the screen viewport:
            clipToViewport: false,
          }),
        ]
      : alphaThresholdFilter;

    this.#renderToCacheContainer.addChild(this.#inkSprite);

    if (text !== undefined) {
      this.text = text;
    }
  }

  get text(): string {
    return this.#currentText;
  }

  set text(textInput: number | string) {
    const str = printableString(textInput);

    if (this.#currentText === str) {
      return;
    }

    this.#currentText = str;
    this.#bake();

    this.#startFlash();
  }

  /**
   * re-rasterises the ink from the font and captures it (with any filters
   * pre-applied) into the render-cache sprite, exactly as the sprite-per-char
   * layout was captured
   */
  #bake() {
    const oldInkTexture = this.#inkSprite.texture;
    this.#inkSprite.texture = rasteriseInk(
      this.#currentText,
      this.#fontVariant,
      this.#resolution,
    );
    if (oldInkTexture !== Texture.EMPTY) {
      oldInkTexture.destroy(true);
    }

    this.#renderToCacheContainer.visible = true;
    // pad out to capture the outline:
    this.#renderToCacheContainer.boundsArea = new Rectangle(
      -1,
      -1,
      (this.#contentWidth() + 2) * this.#widthMult,
      (hudCharTextureSize.h + 2) * this.#heightMult,
    );

    if (this.#renderCacheSprite.texture !== Texture.EMPTY) {
      // destroy the existing texture and its source:
      this.#renderCacheSprite.texture.destroy(true);
    }

    this.#renderCacheSprite.texture = renderContainerToTexture(
      this.#pixiRenderer,
      this.#renderToCacheContainer,
    );

    this.#renderCacheSprite.x =
      -this.#renderCacheSprite.texture.frame.width / 2;

    this.#renderToCacheContainer.visible = false;
  }

  set colour(value: Color) {
    this.#colour = value;
    if (this.#flashTimeout === undefined) {
      this.tint = value;
    }
  }

  set flashColour(value: Color | undefined) {
    this.#flashColour = value;
  }

  #startFlash() {
    if (this.#flashColour === undefined) {
      return;
    }

    clearTimeout(this.#flashTimeout);
    this.tint = this.#flashColour;
    this.#flashTimeout = setTimeout(() => {
      this.#flashTimeout = undefined;
      this.tint = this.#colour;
    }, flashDurationMs);
  }

  #contentWidth(): number {
    return this.#inkSprite.texture === Texture.EMPTY ?
        0
      : this.#inkSprite.texture.frame.width;
  }

  override destroy(options?: Parameters<Container["destroy"]>[0]): void {
    clearTimeout(this.#flashTimeout);
    if (this.#inkSprite.texture !== Texture.EMPTY) {
      this.#inkSprite.texture.destroy(true);
    }
    // always destroy the cached texture/source when the text container is destroyed:
    this.#renderCacheSprite.destroy({ texture: true, textureSource: true });
    super.destroy(options);
  }
}
