name: Check generated files are up-to-date

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  checkGenUpToDate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 25.x
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm gen:types
      - name: Check gen:types is up-to-date
        run: git diff --exit-code -- src/_generated || (echo "Run 'pnpm gen:types' locally and commit the changes." && exit 1)

      - run: pnpm gen:roomSchema
      - name: Check gen:roomSchema is up-to-date
        run: git diff --exit-code -- src/_generated || (echo "Run 'pnpm gen:roomSchema' locally and commit the changes." && exit 1)

      - run: pnpm gen:dbTypes
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - name: Check gen:dbTypes is up-to-date
        run: git diff --exit-code -- src/_generated || (echo "Run 'pnpm gen:dbTypes' locally and commit the changes." && exit 1)

      - run: pnpm gen:roomsPatch
      - name: Check gen:roomsPatch is up-to-date
        run: git diff --exit-code -- src/_generated || (echo "Run 'pnpm gen:roomsPatch' locally and commit the changes." && exit 1)

      - run: pnpm gen:rooms
      - name: Check gen:rooms is up-to-date
        run: git diff --exit-code -- src/_generated || (echo "Run 'pnpm gen:rooms' locally and commit the changes." && exit 1)
